name: summarizer-webapp

services:
  shortener:
    image: shortener-service
    build:
      context: ./shortener
      dockerfile: Dockerfile
    network_mode: "host"

  reteller:
    image: reteller-service
    build:
      context: ./reteller
      dockerfile: Dockerfile
    network_mode: "host"

  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    network_mode: "host"

  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    network_mode: "host"
